apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: "v1.0.22"
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: default
      interval: 1h
