apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  force: false
  interval: 10m0s
  path: ./apps/clusters/minikube
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
